<a href="https://colab.research.google.com/github/Anchayadav/AutoTS/blob/main/How_to_save_a_Machine_Learning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
#from sklearn.utils import Shuffle

data=pd.read_csv('student-mat.csv')

data=data[['G1','G2','G3','studytime','failures','absences']]
predict ='G3'

x=np.array(data.drop([predict],1))
y=np.array(data[predict])


xtrain,xtest,ytrain,ytest =train_test_split(x,y,test_size=0.2)
model= LinearRegression()
model.fit(xtrain,ytrain)

import pickle
with open('pickle_model','wb') as file:

    pickle.dump(model,file)


<ipython-input-1-301b0f9d0f0e>:12: FutureWarning: In a future version of pandas all arguments of DataFrame.drop except for the argument 'labels' will be keyword-only.
  x=np.array(data.drop([predict],1))


In [ ]:
with open('pickle_model','rb') as file:
  model =pickle.load(file)

  prediction =model.predict(xtest)
  for i in range(len(prediction)):
    print(prediction[x],xtest[x],[ytest[x]])

[[ 9.24626334  7.24950829  9.4270793  15.6144851   7.24950829]
 [ 9.24626334  9.24626334  9.4270793  15.6144851  18.93961026]
 [ 4.56733244 12.95747736  9.4270793  15.16332603 15.21543255]
 ...
 [15.21543255 12.95747736  6.79895545 15.16332603 15.16332603]
 [ 6.35566113 15.27978712  6.79895545 15.6144851  15.6144851 ]
 [12.95747736 10.78444272  6.79895545 15.6144851   9.24626334]] [[[10 10  3  2  8]
  [ 8  8  2  0  0]
  [ 8  9  1  1 38]
  [16 15  2  0 11]
  [ 8  8  2  0  0]]

 [[10 10  3  2  8]
  [10 10  3  2  8]
  [ 8  9  1  1 38]
  [16 15  2  0 11]
  [18 18  1  0  8]]

 [[ 6  5  1  0 14]
  [13 13  2  0  2]
  [ 8  9  1  1 38]
  [14 15  2  0  4]
  [15 15  2  0  2]]

 ...

 [[15 15  2  0  2]
  [13 13  2  0  2]
  [ 9  7  2  1 20]
  [14 15  2  0  4]
  [14 15  2  0  4]]

 [[ 5  8  2  3  0]
  [14 15  1  0  3]
  [ 9  7  2  1 20]
  [16 15  2  0 11]
  [16 15  2  0 11]]

 [[13 13  2  0  2]
  [11 11  1  0  0]
  [ 9  7  2  1 20]
  [16 15  2  0 11]
  [10 10  3  2  8]]] [array([[10,  0,  8, 15,  0]