<a href="https://colab.research.google.com/github/Anchayadav/AutoTS/blob/main/Student_Grades_Prediction_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
#from sklearn.utils import Shuffle

data=pd.read_csv('student-mat.csv')
data.head()

school sex  age address famsize Pstatus  Medu  Fedu     Mjob      Fjob  ...  \
0     GP   F   18       U     GT3       A     4     4  at_home   teacher  ...   
1     GP   F   17       U     GT3       T     1     1  at_home     other  ...   
2     GP   F   15       U     LE3       T     1     1  at_home     other  ...   
3     GP   F   15       U     GT3       T     4     2   health  services  ...   
4     GP   F   16       U     GT3       T     3     3    other     other  ...   

  famrel freetime  goout  Dalc  Walc health absences  G1  G2  G3  
0      4        3      4     1     1      3        6   5   6   6  
1      5        3      3     1     1      3        4   5   5   6  
2      4        3      2     2     3      3       10   7   8  10  
3      3        2      2     1     1      5        2  15  14  15  
4      4        3      2     1     2      5        4   6  10  10  

[5 rows x 33 columns]

In [ ]:
data =data[['G1','G2','G3','studytime','failures','absences']]
predict = 'G3'
x=np.array(data.drop([predict],1))
y=np.array(data[predict])


from sklearn.model_selection import train_test_split
xtrain,xtest,ytrain,ytest =train_test_split(x,y,test_size=0.2,random_state=42)


<ipython-input-5-03c30fbacc1f>:3: FutureWarning: In a future version of pandas all arguments of DataFrame.drop except for the argument 'labels' will be keyword-only.
  x=np.array(data.drop([predict],1))


In [ ]:
linear_regression =LinearRegression()
linear_regression.fit(xtrain,ytrain)
accuracy =linear_regression.score(xtest,ytest)
print(accuracy)


0.7821754247320556


In [ ]:
preeidtion =linear_regression.predict(xtest)
for i in range(len(preeidtion)):
  print(preeidtion[x],xtest[x],[ytest[x]])

[[12.70478596 18.6925959   3.42583945  6.01113762 18.6925959 ]
 [12.70478596 12.70478596  3.42583945  6.01113762  7.87300271]
 [ 7.10011213  7.22885591  3.42583945  8.52243043 14.95294333]
 ...
 [14.95294333  7.22885591 12.20306263  8.52243043  8.52243043]
 [ 6.26901605 13.65241561 12.20306263  6.01113762  6.01113762]
 [ 7.22885591 12.6388124  12.20306263  6.01113762 12.70478596]] [[[12 13  2  0  0]
  [19 18  2  0  2]
  [ 3  5  2  1  8]
  [ 8  8  1  3  2]
  [19 18  2  0  2]]

 [[12 13  2  0  0]
  [12 13  2  0  0]
  [ 3  5  2  1  8]
  [ 8  8  1  3  2]
  [ 9  9  2  2 11]]

 [[ 9  7  2  0 18]
  [ 8  8  2  0  0]
  [ 3  5  2  1  8]
  [ 8  9  2  0  8]
  [14 15  2  0  0]]

 ...

 [[14 15  2  0  0]
  [ 8  8  2  0  0]
  [14 12  1  0  3]
  [ 8  9  2  0  8]
  [ 8  9  2  0  8]]

 [[ 7  7  3  0  6]
  [12 14  3  0  1]
  [14 12  1  0  3]
  [ 8  8  1  3  2]
  [ 8  8  1  3  2]]

 [[ 8  8  2  0  0]
  [11 13  2  0  2]
  [14 12  1  0  3]
  [ 8  8  1  3  2]
  [12 13  2  0  0]]] [array([[13, 18,  5, 10, 18]